### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-hammer#24]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.8 is released, we'll want to test WP Hammer to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test WP Hammer on WordPress 5.8
- [x] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a release

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by BBerg10up** [comment]
All set. Logged one minor enhancement (assuming this is due to moving from classic > gutenberg):
https://github.com/10up/wp-hammer/issues/27

Bumped tested up to version:
https://github.com/10up/wp-hammer/commit/3943c724b9ba0b4ebfc56d8a71e37c95946fd874
