### ISSUE TITLE
Pruning by post type results in error

### ISSUE THREAD

**Issue by RobjS** [10up/wp-hammer#25]
**Describe the bug**

According to the README, it should be possible to prune a specific post type, e.g.

```
wp ha -l posts=page.100.post_date
```

To remove all but the 100 most recent posts of type "page". However, this command results in an error.

**Steps to Reproduce**

1. Run `wp ha -l posts=page.100.post_date`
2. Error starting `WordPress database error Unknown column '100' in 'order clause' for query SELECT COUNT(*) FROM wp_posts order by 100 DESC` is returned

**Expected behavior**
All posts of type "page", except the 100 with most recent post_dates, are removed from the database.

**Comment by ivankruchkoff** [comment]
Thanks for raising the bug, and also for putting out the PR @RobjS
